### ISSUE TITLE
Android/iOS beer trivia

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#10]
Taka luźna myśl - fajna forma spotkań dla deweloperów. Organizator wymyśla zestaw pytań (o rosnącej trudności) związanych, następnie zawodnicy walczą próbując odpowiedzieć jak najlepiej na jak największą liczbę pytań. 

Oczywiście należałoby to zrobić rozłączenie dla iOS/Android. 

Przykład slajdów z takiego spotkania tutaj: https://speakerdeck.com/mattt/nshipster-pub-quiz-number-1 Chris E. mówił, że wyszło prześwietnie. Spróbujmy to zrobić u nas ;)

**Comment by potiuk** [comment]
Ja osobiście nie czuję quizów :D  Brałem udział w kilku (w sensie
obserwowałem) ale raczej nigdy mnie to nie kręciło.

Ale może hipsterzy NS będą mieli frajdę :)

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-01-28 Pawel Dudek notifications@github.com

**Comment by paweldudek** [comment]
Dla mnie to jest mega fajne. Pomęczę parę osób, może uda nam się coś fajnego zrobić w klimacie MW.

**Comment by paweldudek** [comment]
RW podał ciekawą koncepcję tego: co spotkanie podczas przerwy rzucamy parę pytań z iOS/Android, raczej prostych. Zapisujemy punktację na każdym spotkaniu, i po paru spotkaniach osoba, która zdobyła najwięcej punktów dostaje jakąś nagrodę (możemy zacząć skromnie, od np koszulki). 

Thoughts?

**Comment by potiuk** [comment]
Jak pisałem - nie mam zdania :(. Mnie takie quizy nie kręcą - choć
widziałem że są ludzie dla których może to być fajna zabawa ;) .

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-18 15:51 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Jarku, ranisz mnie dogłębnie :( Ale myślę, że Roberta W. możemy w to wciągnąć, jemu ten pomysł bardzo się spodobał. ;)
