### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#12]
Podczas szalonej rozmowy z Maćkiem O. padła interesująca propozycja - może zrobilibyśmy technologicznego bloga o rzeczach w iOS i Android?

Myślałem o formie obj.io - oni robią jedno wydanie na miesiąc, 5-6 rozbudowanych artykułów. Moglibyśmy zrobić coś podobnego, podzielić na iOS/Android/design i wrzucić pod markę MW/MCE.

Thoughts?

**Comment by wojtekerbetowski** [comment]
to może lepiej po prostu kontrybuować do obj.io? :-)

2014-02-05 Pawel Dudek notifications@github.com:

> Podczas szalonej rozmowy z Maćkiem O. padła interesująca propozycja - może
> zrobilibyśmy technologicznego bloga o rzeczach w iOS i Android?
> 
> Myślałem o formie obj.io - oni robią jedno wydanie na miesiąc, 5-6
> rozbudowanych artykułów. Moglibyśmy zrobić coś podobnego, podzielić na
> iOS/Android/design i wrzucić pod markę MW/MCE.
> 
> Thoughts?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/12
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by potiuk** [comment]
Albo do swoich firmowych blogów (oferujemy gościnny wpis u nas, jak już
wdrożymy nową stronę :) ).

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-02-06 Wojciech Erbetowski notifications@github.com:

**Comment by potiuk** [comment]
Obejrzałem film z wykładu Chris-a (zajebisty) i teraz rozumime Pawle o czym mówiłeś. To jest bardzo słuszna koncepcja, żeby coś w tym stylu zacząć. Przy okazji publikacji filmów na MCE rozmawiałem z Krzyśkiem Zabłockim. On jest bardzo chętny żeby razem z nami coś w tym temacie zrobić - a myślę że jest do tego naprawdę świetny (mielibyśmy od razu boost-a na publikę). On myślał o tym żeby zrobić Podcasta, a obaj zgadzamy się z Krzyśkiem w tym, że jeśli robić coś takiego, to na 110% - tak żeby było na światowym poziomie i żeby od razu było jasne, że robimy coś świetnego u nas w Polsce (tak jak sugerował to Chris w swoim Talku). Zrobienie tego profesjonalnie (cokolwiek by to miało być) to duży wysiłek i zobowiązanie (regularne), ale myślę że warto go ponieść - warunkiem jednak jest znalezienie kilku naprawdę dobrych osób (takich jak Krzysiek), które mogłyby do tego się dołożyć. Moglibyśmy to zrobić pod egidą MCE/MW i przy okazji robić dobry PR MCE++ za rok. Dla odmiany - powinno być to nie tylko obj-c ale ogólnie - mobile (powody te same o których już mówiłem, ale tu dużo łatwiej to zrobić - podział na technologie + wspólne posty). 

Krzysiek na razie ciśnie na wrzucenie nowego produktu, ale od połowy Marca bardzo chętnie się tym zajmie. Moglibyśmy teraz wytypować kilku kandydatów ze środowiska i pogadać z nimi, co o tym sądzą. 

Co myślicie ?

**Comment by paweldudek** [comment]
Uuuuf, cieszę się, że to jednak nie jest tragiczny pomysł ;)

Z merytorycznej strony:
- W 100% zgadzam się, że jak już to trzeba to robić na 110% możliwości - pokażmy światu, że w naszym kraju żyją świetni inżynierowie
- Forma podcastu - nie wszyscy słuchają podscatów. Prawie każdy czyta artykuły. Nie wszystkim chce się słuchać podcastu, by znaleźć ten kawałek wiedzy w nim zawarty. Artykuł można szybko przewinąć. Ja jestem za artykułami. 
- Mogę pociągnąć za sznurki i zobaczyć, kto z moich kontaktów byłby tym zainteresowany. Obawiam się tylko, że oni chcieliby to zrobić pod własną flagą (np Cocoaheads Krk etc), ale możemy zobaczyć. W WWA mamy też parę niezłych osób: Krzysiek, Bartek, Robert. Się znajdzie ludzi ;)
- Ja bardzo, bardzo bym chciał żeby to było ogólno-mobilne. Tj, część dla iOS, część dla Androida i część wspólna. Plus też coś o UI/UX. ;)

Reasumując: chcemy to zrobić, potrzebujemy kandydatów. Nominujcie ludzi, będziemy się z nimi po kolei kontaktować.

Ja nominuję:
- Bartosz Ciechanowski (bardzo mocno, jego artykuły odbiły się echem w środowisku, pytanie tylko, czy Macoscope będzie chciało go wypuścić ze swojego bloga)
- Robert Wijas (mocno, Robert świetnie pisze i ma świetne podejście)
- Łukasz Warchoł (cza by przetestować)
- Alek Zubala (cza by przetestować)

Thoughts?

**Comment by potiuk** [comment]
Rozpytam. Mam też paru kandydatów, ale większą listę w przyszłym tygodniu
dorzucę - jak popytam.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 20:05 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by potiuk** [comment]
- UI/UX - możemy w to zaangażować nasz dział kreatywny - żeby też podesłali
  parę kontaktów. Chętnie do nich zagadam w temacie.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 21:55 GMT+01:00 Jarek Potiuk jarek@potiuk.com:

**Comment by paweldudek** [comment]
Tak też myślałem. :) Czekam na odpowiedź!

W dniu 17 lutego 2014 21:58 użytkownik Jarek Potiuk <
notifications@github.com> napisał:

**Comment by potiuk** [comment]
Na razie odpowiedzi od Agnieszki nie mam :( czyli raczej nic z tego ...

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 15:13 GMT-06:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Dang. Ja mam kontakt do takiej dziewczyny z Krakowa od UX, zobaczę, może da się tam coś ruszyć.

**Comment by potiuk** [comment]
Wysłałem też do naszego teamu UX i dam znać - sorry za opóźnienia na
łączach, ale byłem raczej daleko, na długo i strasznie zajęty. Poprawiam
się sukcesywnie.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-03-10 9:32 GMT-06:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Emi jest zainteresowana, ale max jeden artykuł na parę miesięcy, więc potrzebowalibyśmy trochę więcej ludzi od UX jeśli chcemy też to promować.

**Comment by potiuk** [comment]
Sytuacja się rozwija. Od nas parę UX-owych i technicznych blogów będzie do
cross-postowania. Nasi UX-owcy się też rozglądają. Dam znać jak będzie
więcej wiadomo.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-03-12 19:34 GMT+01:00 Pawel Dudek notifications@github.com:
