### ISSUE TITLE
TDD Workshop

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#3]

**Comment by potiuk** [comment]
Jeszcze tu nic nie ma, ale uważam, że to świetny pomysł :). Rozumiem że to któryś ze speakerów z MCE będzie robił :) ?

**Comment by paweldudek** [comment]
To akurat we własnym zakresie, nie bardzo mamy maniaka od TDD którego moglibyśmy do tego wykorzystać ;) Jon Reid trochę daleko mieszka :P

**Comment by wojtekerbetowski** [comment]
OK, proponuję w marcu to zrobić.

Potrzebujemy określić dokładną datę i format.
Proponuję max 30 osób, łączeni 4 prowadzących przez całą sobotę (po ok 2h każdy prowadzi,
wszyscy pomagają uczestnikom cały czas).
Co Ty na to? np 17 marca.

**Comment by paweldudek** [comment]
Brzmi zajefajnie :) 17sty marca jest to akurat poniedziałek :D Ale 15sty też byłby dobry ;)

**Comment by potiuk** [comment]
TDD workshop jest super!. Mnie akurat nie ma ani 15-go ani 17-go ale myślę
że nie jestem potrzebny :)

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

**Comment by paweldudek** [comment]
Ok, zakładam, że chcielibyśmy zrobić to bardziej około-mobile. iOS/Android? Czy tylko iOS? Czy tylko Android? Czy może podzielić na dwa? TDD w obu przypadkach działa tak samo, z drugiej strony - inne platformy i zapewne inne narzędzia. Z trzeciej strony - ludzie może nauczą się czegoś nowego, np z innej strony. 

Kogo próbujemy złapać na prowadzących? Ja nie wiem, czy mam dostatecznie dużo skilla z TDD na to, ale mogę spróbować. Wojtku, może chcesz pomóc? ;) 

Zapytam się Łukasza W. od nas, czy by nie chciał pomóc, on jest sporym ewangelistą tego. Thoughts?

**Comment by wojtekerbetowski** [comment]
Polecam jeszcze Maćka Oczko żeby wprowadził DI, to na pewno.
I jak Łukasz zechce to we trzech już poprowadzicie :-)

Zrobiłbym czysty iOS, będzie łatwiej.

2014-02-04 Pawel Dudek notifications@github.com:

> Ok, zakładam, że chcielibyśmy zrobić to bardziej około-mobile.
> iOS/Android? Czy tylko iOS? Czy tylko Android? Czy może podzielić na dwa?
> TDD w obu przypadkach działa tak samo, z drugiej strony - inne platformy i
> zapewne inne narzędzia. Z trzeciej strony - ludzie może nauczą się czegoś
> nowego, np z innej strony.
> 
> Kogo próbujemy złapać na prowadzących? Ja nie wiem, czy mam dostatecznie
> dużo skilla z TDD na to, ale mogę spróbować. Wojtku, może chcesz pomóc? ;)
> 
> Zapytam się Łukasza W. od nas, czy by nie chciał pomóc, on jest sporym
> ewangelistą tego. Thoughts?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-34093701
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by potiuk** [comment]
Faktycznie samego warsztatu lepiej nie mieszać iOS/Android, ale ....

Może zorganizować dwa bliźniacze warsztaty w tym samy czasie z małym
teoretycznym wstępem na temat TDD w ogóle - może nawet niekoniecznie
specyficznie dla mobile ale bardziej ogólne rzeczy - po co TDD, jakie
problemy rozwiązuje, jakie ogólne techniki są używane (mocki itd), może
troche o zaletach cyklu red-green-refactor etc.. . To może np. właśnie
Wojtek zrobić :). A potem rozejście się w podgrupach - za to po warsztatach
after-party z mieszaniem androidowców i iOS-owców w celu wymiany
doświadczeń z warsztatów.

A co do androidowego TDD - to założe się że Rudy będzie chciał (od
poniedziałku pracownik uTestu - jeśli jeszcze Pawle nie wiesz), może też
Mateusz no i pewnie z Taptery by się ktoś androidowy znalazł ... Możemy
jeszcze poszukać parę innych osób.

Można by się też zastanowić nad sprowadzeniem jakichś praktyków spoza
granicy jako mentorów ... Jakby się dało Jona Reida np. to by było super,
ale obawiam się że finansowo będzie słabo :(. Ale może np. Chris kogoś
podeśle, możemy też popytać naszych wschodnich sąsiadów. Co myślicie? Czy
lepiej żeby te warsztaty były po polsku?

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-05 Wojciech Erbetowski notifications@github.com:

**Comment by wojtekerbetowski** [comment]
Ja bym się ograniczył do iOS. Zaczynamy ze szkoleniami i tak nam będzie
łatwiej i z miejscem i z prowadzącymi.
Know how szybko możemy przekuć w kolejne warsztaty, nie musimy na tych
poprzestać.
Co do gości z zagranicy to też niepotrzebnie komplikuje sprawę. Oni są
fajni żeby wypromować wykłady,
ale na taki warsztat i tak będzie full chętnych (by full I mean 30 :-)).

**Comment by potiuk** [comment]
Co do zagranicznych gości - fakt.

Ale ja bym jednak zapytał Rudego/Mateusza czy by nie chcieli się
zaangażować - był przynajmniej jeden komentarz na MCE że powinno być więcej
Androida  - więc popyt jest. W "szerszym" założeniu MW jest to. że ogólnie
chcemy budować wspólnotę mobile a nie dwie oddzielne iOS/Android. Jeśli
tylko znajdziemy kogoś kto te warsztaty poprowadzi i zorganizuje (potencjał
jest) - to niewiele zwiększa to kwestie organizacyjne (trochę inne miejsce
i więcej pizzy do zamówienia) a jest okazja żeby zintegrować trochę
środowisko. Powinniśmy też myśleć o tych "większych" celach. Przy okazji -
osoby/osoba które znajdziemy do organizacji warsztatów mogą nam wypełnić
wakat na Androidowego organizatora MW. Będzie okazja wciągnąć kogoś
bardziej. IMHO - same zalety a przy okazji możemy rozwiązać kwestię
Androidowego filara "MW".

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-05 Wojciech Erbetowski notifications@github.com:

**Comment by wojtekerbetowski** [comment]
-1

uważam, że warsztaty mają zupełnie inną filozofię i integrowanie ludzi
którzy cały dzień uczą się czego innego nie ma sensu. Nie ma tak naprawdę
wspólnego tematu, nie ma jakiej części wspólnej wyciągać.
Chodzi Ci o zrobienie zupełnie nowych warsztatów w tym samym miejscu i
czasie.
A ja wolę, żeby zacząć warsztaty najprościej jak się da, bez zbędnych
komplikacji.

Androidowe możemy robić swoją drogą, jeśli miejsce (np uczelnia) będzie
sprzyjało wielu warsztatom naraz, sponsor weźmie obiad dla wszystkich itd
to nie ma problemu, żeby były obok siebie, ale nie zaczynajmy od tego
założenia.

**Comment by paweldudek** [comment]
Panowie, pozostawiliście mnie w rozdarciu :(

Powiem Wam, jak ja to widzę. Z jednej strony w 100% zgadzam się z Jarkiem, że powinniśmy jak najbardziej integrować wszystkie grupy developerów mobilnych, i iOS, i Android. Tak samo wydaje mi się, że znalezienie ludzi do poprowadzenia będzie największym "kosztem dodatkowym" (większa sala i więcej jedzenia to będzie małe zmartwienie). Plus wakat by nam się przydało wypełnić ;)

Druga strona medalu, że faktycznie to będzie bardzo ciężko połączyć. Można zrobić wstępną, wspólną prezentację czemu warto pisać (ja ja ja! Ja chciałbym o tym opowiedzieć ;)), ale reszta już raczej będzie musiała być rozłączona, zapewne w dwóch osobnych salach. Nie wiem, jak to można dobrze połączyć z networkingiem ponad wspólne piwo po spotkaniu. 

Zróbmy tak: gadałem z Łukaszem Warchołem i on byłby chętny. Maciej Oczko również. To daje nam 3 osoby do prowadzenia od strony iOS, na pewno znajdzie się jeszcze z jedna osoba. Zacznijmy od iOS, jak się uda to rozszerzmy na Androida ze wspólnym wstępem, reszta osobno. 

Thoughts?

**Comment by potiuk** [comment]
Rozdarcie jest dobre. Nie ma to jak ścieranie się opinii :D.

Pewnie - jeśli łatwiej będzie zrobić dla iOS-a najpierw w celach
"rozkręcenia" - to tak zróbmy, ale ja uparcie twierdzę, że jest bardzo duża
część wspólna. Nie zaczynajmy od tego założenia ale jeśli (np.) Paweł
Byszewski by był chętny, to dlaczego by nie spróbować zrobić to równolegle?
Komplikacji widzę niewiele - raczej synergia (wspólny marketing na MW/MCE,
jedna strona do rejestracji, silniejsza pozycja w rozmowach ze sponsorami,
cateringiem etc.). Jeśli było by to na uczelni, to czy dwie sale, czy jedna
już nie powinno mieć tak dużego znaczenia.

Założenia i filozofia: po pierwsze po co to robimy, co chcemy osiągnąć,
przekonanie mobilnych deweloperów że można TDD w mobilkach robić. Techniki,
narzędzia etc. są oczywiście różne, ale na przykład jakby pisać tą samą
aplikację na iOS i Android-a w ramach warsztatu TDD to można by na
przysłowiowym "piwie" porozmawiać o tym, jakie testy mają sens, porównać to
co było zrobione iOS/Android, porozmawiać jedni z drugimi o dostępnych
narzędziach w ramach obu platform. Wtedy mogło by się na przykład okazać,
że część rozwiązań z iOS-a można by przenieść na Androida albo odwrotnie...
Może to być zaczątek jakichś open-source'owych projektów na przykład.

Wydaje mi się że bardzo mało ludzie między platformami rozmawiają, a
powinniśmy naszymi działaniami to stymulować.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-05 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Jarku, 

Zgadzam się, że organizacyjnie będzie niewielka różnica. Zgadzam się, że warto spróbować zespoić te dwa środowiska bardziej. Idea networkingu po brzmi fajnie. Ale wciąż wydaje mi się, że zasadnicza część warsztatów (może poza wstępem) musi być rozłączona. 

Nie mniej, możemy spróbować zrobić dwa w jednym i zobaczymy, co z tego wyjdzie. Potem oceni się, czy warto to łączyć, czy nie. 

Thoughts?

**Comment by potiuk** [comment]
Tak jak napisałem - uważam ze lepiej by bylo razem ale  jeśli lepiej jest
wam zrobić oddzielnie i zobaczyć jak to wyjdzie - to róbcie najpierw iOS.
Twoja decyzja Pawle.

Jeśli uda się kogoś dobrać od Androida (mogę pomoc szukać i podsylac
kandydatów - tak jak Pawła Byszewskiego) to przede wszystkim decyzja czy
robić, kiedy, czy w tym samym czasie czy w oddzielnym należy do Ciebie i
tej osoby.

J.

**Comment by paweldudek** [comment]
Jeśli decydujemy się robić szkolenie z Androida i iOS'a to _nic_ nie stoi na przeszkodzie, by zrobić je obok siebie. Pragmatycznie, mniej roboty. ;) 

Zróbmy tak: iOS robimy na 100%, jak Paweł będzie chciał/ogarnie Androida na ten sam termin: zróbmy razem. W aktualnym świetle jestem za złączeniem tego. 

Odezwę się do Pawła right away.

**Comment by wojtekerbetowski** [comment]
Jednak musimy się zdecydować już teraz ponieważ miejsce na 30 osób możemy w
miarę szybko znaleźć (np jedna z iOSowych firm), a na 60 wchodzi w grę
jakaś uczelnia, bądź dedykowane miejsce do szkoleń.

Ja wciąż pozostaję zwolennikiem opcji iOS only. Androidowe możemy zrobić np
miesiąc później wykorzystując know how. Druga sprawa to format. Żeby pokryć
koszty miejsca i obiadu, możemy przyjąć niewielką opłatę.

Inny pomysł, z którym bardzo chętnie bym zaczął, to 8h za 8h. Słyszałem o
takiej akcji ostatnio,
że organizujemy 8 godzinne szkolenie, ale w zamian uczestnicy po szkoleniu
przeznaczają
8h każdy na odpracowanie szkolenia. Może to być pomoc w organizacji
kolejnego, szukanie sponsora, niemal cokolwiek (my wybieramy zadania,
uczestnicy się do nich przypisują).

**Comment by paweldudek** [comment]
Dobra, trzeba coś zdecydować. 

Zróbmy iOS only, zaraz potem Android only, a potem zrobimy łączone. Chętnych nam na pewno nie zabraknie ;)

Let's start small, nie mamy wielkiego doświadczenia w tym. 

Kropka! Chyba, że ktoś (@Jarek) stawia liberum veto ;)

Finansowania: Jarek wspomniał, że Wikia może być chętna zostać sponsorem tej całej imprezy. Jestem za tym, że jeśli uda nam się znaleźć sponsora - bierzemy sponsora i robimy wejście za darmo. 

Idea 8 za 8 - mega ciekawe. I naprawdę mi się podoba! Jeśli nie uda nam się znaleźć sponsora to rozważyłbym to albo opłatę za wstęp. W modelu 8 za 8 nie wiem, z czego zapłacimy za jedzenie ludziom tylko :( Chyba, że dwie osoby dostaną 8 h gotowania dla ludzi...? :P

Thoughts?

**Comment by potiuk** [comment]
Jakie veto ? :). Jak to mówi moja żona (Choć może w tym przypadku to nie
najlepsze porównanie ): "Twój cyrk - twoje małpy".

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-10 Pawel Dudek notifications@github.com:

**Comment by pawelByszewski** [comment]
Cześć Panowie i dzięki za włączenie do tego szanownego grona.
Z chęcią na stałe włącze się do pomagania przy eventach, w przypadku iOS czysto organizacyjnie, a Androida także merytorycznie.
Mi się całkiem podoba pomysł z developmentem tej samej aplikacji równolegle na 2 platformach. Chociaż jeśli wątek Androidowy miałby pokazać TDD w zestawieniu z dwoma najpopularniejszymi DI, to development mógłby iść dosyć wolno.
BTW czy sponsorzy i prelegenci są już w jakikolwiek sposób ogarnięci? Jutro będę miał kontakt z dosyć decyzyjną osobą z allegro, więc moge się zapytać czy Allegro było by zainteresowane sponsorowaniem i czy ma jakieś związane z tym oczekiwania.

**Comment by paweldudek** [comment]
Na dany moment sponsorów ani prelegentów nie mamy. Do części iOS'owej mam
dwóch pewniaków i paru kandydatów na mentorów, natomiast Android jeszcze
nie ruszony. Możesz rzucić to pod Allegro, zobaczymy, co powiedzą.

W dniu 12 lutego 2014 10:57 użytkownik pawelByszewski <
notifications@github.com> napisał:

**Comment by pawelByszewski** [comment]
Co do sponsorowania to Allegro generalnie zapowiada, że jest na tak. Aczkolwiek konkretne deklaracje i szczegóły pojawią się w przyszłym tygodniu.
Mentorów androidowych zacząłem  poszukiwać.
A jest już jakiś pomysł na miejsce?

**Comment by wojtekerbetowski** [comment]
Proponuję za uczelni (np MIMUW). Niskie stawki za sale, dobry internet i
łatwo wszystko załatwić.

2014-02-14 10:32 GMT+01:00 pawelByszewski notifications@github.com:

> Co do sponsorowania to Allegro generalnie zapowiada, że jest na tak.
> Aczkolwiek konkretne deklaracje i szczegóły pojawią się w przyszłym
> tygodniu.
> Mentorów androidowych zacząłem poszukiwać.
> A jest już jakiś pomysł na miejsce?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-35068770
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
Uczelnia na coś takiego brzmi idealnie - gotowa infrastruktura + koszt ;)
Wojtek chcesz się tym zająć czy mogę to wziąć na siebie?

W dniu 14 lutego 2014 11:38 użytkownik Wojciech Erbetowski <
notifications@github.com> napisał:

**Comment by wojtekerbetowski** [comment]
Spoko, jak dla mnie możesz się kontaktować. Człowiek, który Ci pomoże to
Janusz Jabłonowski janusz@mimuw.edu.pl

Możesz się powołać na mnie, czy dać mnie w CC.
Musisz znać termin, na ile osób chcemy salę (na 30 uczestników + 4 trenerów
proponuję 3180,
jest aż za duża, ale poustawiamy sobie fajnie ławki i wsio i jest tam dobry
rzutnik).

2014-02-16 12:42 GMT+01:00 Pawel Dudek notifications@github.com:

> Uczelnia na coś takiego brzmi idealnie - gotowa infrastruktura + koszt ;)
> Wojtek chcesz się tym zająć czy mogę to wziąć na siebie?
> 
> W dniu 14 lutego 2014 11:38 użytkownik Wojciech Erbetowski <
> notifications@github.com> napisał:
> 
> > Proponuję za uczelni (np MIMUW). Niskie stawki za sale, dobry internet i
> > łatwo wszystko załatwić.
> > 
> > 2014-02-14 10:32 GMT+01:00 pawelByszewski notifications@github.com:
> > 
> > > Co do sponsorowania to Allegro generalnie zapowiada, że jest na tak.
> > > Aczkolwiek konkretne deklaracje i szczegóły pojawią się w przyszłym
> > > tygodniu.
> > > Mentorów androidowych zacząłem poszukiwać.
> > > A jest już jakiś pomysł na miejsce?
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-35068770>
> > 
> > > .
> > 
> > ## 
> > 
> > Cheers,
> > 
> > Wojtek Erbetowski
> > http://erbetowski.pl/
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-35072984>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-35194687
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by wojtekerbetowski** [comment]
Czy któraś z firm, z którymi miałeś ostatnio kontakt byłaby zainteresowana wsparciem warsztatu?
Czy decydujemy się na niewielką płatność od uczestników? Pewnie sala na MIMUW jakieś niewielkie pieniądze będzie kosztowała, ale zawsze. Do tego przyda się obiad (dla 30 osób to nawet 1000zł).

**Comment by paweldudek** [comment]
Nikt, poza Manpower, nie garnął się do sponsorowania MW, myślę, że z
warsztatami będzie podobnie. Czekamy na Allegro i ew Estimote. Raczej
nastawiałbym się na płatne warsztaty (nie wiem, jakie są koszty sali na
MIMUW, ale załóżmy nawet 1k + 1k żarło 2k / 30 osób -> jakieś 70 zł, za
cały dzień to imo spoko).

Thoughts?

W dniu 17 lutego 2014 13:05 użytkownik Wojciech Erbetowski <
notifications@github.com> napisał:

**Comment by pawelByszewski** [comment]
Gość ogarniający w Allegro sprawy sponsorowania pojawi sie dopiero jutro w pracy więc jakas odpowiedź nie pojawi się rankiem, ale postaram się go spingować aby dostać chociaż wstępną deklarację. W TouK przedstawiłem także pomysł na warsztaty, ale wiem, że Paweł zagadywał także w sprawie nabliższego spotkania MW więc sprawa się procesuje.
Na razie  mam marny odzew (no może jakiś niesmiały od strony Androida) w kwestii mentorów. 

Z powyższych postów rozumiem, że na marzec jest skupienie tylko na iOS, a android w bliżej nieokreślonej przyszłości?

**Comment by potiuk** [comment]
Ja znowu z nart, więc na chwilę tylko, wieczorem przed snem:

A może powinniśmy uderzyć do tych wszystkich firm (również mniejszych i
średnich) które przysłały ludzi na MCE? Okazało się że jest w Polsce
kilkadziesiąt firm, o których nie mieliśmy pojęcia, a mają wystarczająco
dużo pieniędzy, żeby przysłać ludzi na MCE. Może zamiast 2 większych uda
się zdobyć 10 mniejszych sponsorów (w ten sposób od razu możemy sobie
zwiększyć bazę firm potencjalnie sponsoringowych - co tak, czy inaczej
powinniśmy zrobić). Jest to w pełni legalne (mamy zgodę ludzi na
wykorzystywanie ich adresów w celach organizacji innych imprez - bez
sprecyzowania czy chodzi o sponsoring, czy uczestnictwo).

Trzeba by tylko:
- wyłuskać z naszych danych te firmy (ręczna robota niestety, trzeba by
  przetworzyć 450+ osób w ten sposób - ale wystarczy to zrobić tylko raz i
  będziemy mieli na przyszłość)
- zidentyfikować osobę (najlepiej tą, która była odpowiedzialna za
  płacenie faktur!) - jak będziemy mieli listę firm to łatwo to będzie zrobić
  przeglądając historię contact@mobilecentraleurope.com
- wysłać do nich po jednym mailu na firmę zapraszającą do udziału w
  warsztatach

Ktoś chętny i ma czas na to (heh.. wiem.. nikt nie ma czasu) ?

To oczywiście ręczna i żmudna robota, ale bez jej zrobienia będziemy
obracać się w tym samym zaklętym kręgu firm, które zawsze nękamy do
sponsorowania, a warto by chyba to rozszerzyć, zwłaszcza że nasi
dotychczasowi sponsorzy są "ogólni" a nam potrzeba bardziej "mobilnych" -
zwłaszcza przy takich eventach interesujący są sponsorzy bardziej
technologiczni - czyli idealni są ci, którzy wysłali ludzi na MCE. Jak to
już zrobimy, to mamy świetną w pełni legalną bazę na przyszłość - nawet
jeśli ktoś nie będzie zainteresowany teraz, to zawsze będzie można uderzyć
w przyszłości.

BTW. Napisałem do Agnieszki z wikii - zobaczę co napisze. Dam znać jak
tylko odpowie.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 20:13 GMT+01:00 pawelByszewski notifications@github.com:

**Comment by pawelByszewski** [comment]
BTW o jakiej kwocie mniejwięcej mówimy w przypadku sponsorowania i co oferujemy w zamian? Miejsce na banner? 10min czasu na reklamę?

**Comment by gregwolanski** [comment]
Jarek, ja przy weekendzie mogę się tym zająć.

**Comment by paweldudek** [comment]
@Jarek daj dostęp do tej listy, może uda mi się wygospodarować troszkę
czasu (acz nie gwarantuję).

@Pawel w wiki jest dokument z ceną i co dajemy w zamian.

W dniu 18 lutego 2014 11:35 użytkownik Gregory Wolanski <
notifications@github.com> napisał:

**Comment by pawelByszewski** [comment]
allegro jest wstępnie zainteresowane.
Więc tak aby ustalić aktualny stan organizacyjny:
- ścieżka iOS jest pewna
- ścieżka Android jest mało prawdopodobnna w termiie równoległym do iOS
- na warsztacie będzię max 30 osób per platforma

Sponsoring
1200zł
10min. na reklamę
rozstawienie bannerów

Zgadza się?

**Comment by wojtekerbetowski** [comment]
Super, jak dla mnie się wszystko zgadza.

2014-02-20 10:46 GMT+01:00 pawelByszewski notifications@github.com:

> allegro jest wstępnie zainteresowane.
> Więc tak aby ustalić aktualny stan organizacyjny:
> - ścieżka iOS jest pewna
> - ścieżka Android jest mało prawdopodobnna w termiie równoległym do iOS
> - na warsztacie będzię max 30 osób per platforma
> 
> Sponsoring
> 1200zł
> 10min. na reklamę
> rozstawienie bannerów
> 
> Zgadza się?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-35603338
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
@pawelByszewski jak stoimy ze sponsorem? Coś trzeba załatwić? Potrzebujesz pomocy z czymś? Daj znać!

**Comment by pawelByszewski** [comment]
Na razie cisza, pingowałe allegro w ostatni piątek i sprawa się procesuje :/
A czy mamy może bazę firm, do których można by udeżyć z taką ofertą? lub ewentualnie listę firm, które już o tym wiedzą i nie są zainteresowane?

**Comment by paweldudek** [comment]
Bam, trochę bida.

Niestety nie dysponujemy taką bazą. Ja ostatnio uderzałem do sporej listy
firm, zaraz Ci napiszę listę.

W dniu 6 marca 2014 21:23 użytkownik pawelByszewski <
notifications@github.com> napisał:

**Comment by pawelByszewski** [comment]
posiedzę, poszukam i powysyłam ale już poczekam na listę, aby nie dublować zapytań.

**Comment by paweldudek** [comment]
- TouK
- Airnauts
- Vestiacom
- Connectmedica
- g-force.com.pl
- Mindpower
- Macoscope (chętni, ale na następne spotkanie)
- Javart
- Base
- Codequest
- Estimote

**Comment by potiuk** [comment]
Ja trochę icicles bo jestem w Stanach i raczej mocno zajety,  ale może
warto wrócić do tych firm o których pisałem wcześniej.  Wojtek ma w razie
czego dostęp do tych adresów mailowych/firm z MCE i może warto to
wykorzystać?

J

**Comment by potiuk** [comment]
Icicles = późno ??? . Telefon różne figle plata.

**Comment by paweldudek** [comment]
Na szkolenie za późno, ale może warto by było zbudować w ogóle bazę takich firm, które byłyby zainteresowane sponsorowaniem. @wojtekerbetowski dasz dostęp do tej listy?

**Comment by wojtekerbetowski** [comment]
Nie ma jednej - wspólnej listy. Każda inicjatywa ma swoje kontakty.
Jakby co możemy założyć na mobile nową :-) mergowanie wymaga zgód
właścicieli, ale też się da.

**Comment by paweldudek** [comment]
Ok, czyli we're all alone ;) Ja póki co ponad listę powyżej nie mam nic. @pawelByszewski pisałeś gdzieś jeszcze?

**Comment by potiuk** [comment]
Wrócę w środę to wyciągnę tę listę.

J.

**Comment by wojtekerbetowski** [comment]
Ah chodzi o listê firm uczestników z MCE, spoko.

2014-03-10 16:57 GMT+01:00 Jarek Potiuk notifications@github.com:

> Wrócê w ¶rodê to wyci±gnê tê listê.
> 
> J.
> On 10 Mar 2014 10:47, "Pawel Dudek" notifications@github.com wrote:
> 
> > Ok, czyli we're all alone ;) Ja póki co ponad listê powy¿ej nie mam nic.
> > @pawelByszewski https://github.com/pawelByszewski pisa³e¶ gdzie¶
> > jeszcze?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-37197254>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/3#issuecomment-37198557
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
Yup! To jak będzie lista to jakoś ogarniemy. :)

W dniu 10 marca 2014 16:59 użytkownik Wojciech Erbetowski <
notifications@github.com> napisał:

> Ah chodzi o listê firm uczestników z MCE, spoko.
> 
> 2014-03-10 16:57 GMT+01:00 Jarek Potiuk notifications@github.com:
> 
> > Wrócê w ¶rodê to wyci±gnê tê listê.
> > 
> > J.

**Comment by pawelByszewski** [comment]
Pisałem do kilki firm, które byly sponsorami Confitury i mają jakiś związek z Mobilnym światem ale jak na razie odzew jest mizerny. Obiecująco wygląda sprawa w Allegro ale procesownie decyzji trwa całe wieki więc raczej na warsztaty się nic nie wyklaruje. Dzisiaj odbyłem jedną rozmowę z kimś odrobinę wyżej w hierarchii wię może sprawa nabierze tempa.

**Comment by potiuk** [comment]
Ja pisałem jeszcze raz do Agnieszki z wikii - odpisała, że są zajęci teraz
(nowe biuro), ale że w przyszłości bardzo chętnie.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-03-12 5:17 GMT-05:00 pawelByszewski notifications@github.com:
